export const CREATE_BEST_SALES_LIST = "CREATE_BEST_SALES_LIST";

export const CREATE_CATEGORY_LIST = "CREATE_CATEGORY_LIST";
export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const OPEN_SIGNIN_MODAL = "OPEN_SIGNIN_MODAL";
export const OPEN_INFO_MODAL = "OPEN_INFO_MODAL";
export const OPEN_LOGOUT_CONFIRM_MODAL = "OPEN_LOGOUT_CONFIRM_MODAL";
export const OPEN_DELETE_CONFIRM_MODAL = "OPEN_DELETE_CONFIRM_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";

export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const UPDATE_USER = "UPDATE_USER";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";